//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClosDotNet.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClosDotNet.Resources.Resources.BusinessResources", typeof(BusinessResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Strategy.
        /// </summary>
        public static string LabelAccountStrategy {
            get {
                return ResourceManager.GetString("LabelAccountStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Bank Position (e.g.: main or secondary banker), Our Objective, Action Plan or Cross Marketing Opportunity.
        /// </summary>
        public static string LabelAccountStrategy2 {
            get {
                return ResourceManager.GetString("LabelAccountStrategy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrower Background.
        /// </summary>
        public static string LabelBorrowerBackground {
            get {
                return ResourceManager.GetString("LabelBorrowerBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Incorporation / Relationship Started / Business Description.
        /// </summary>
        public static string LabelBorrowerBackground2 {
            get {
                return ResourceManager.GetString("LabelBorrowerBackground2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Activities.
        /// </summary>
        public static string LabelBusinessActivities {
            get {
                return ResourceManager.GetString("LabelBusinessActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature of Business (e.g.: core business &amp; etc).
        /// </summary>
        public static string LabelBusinessActivities2 {
            get {
                return ResourceManager.GetString("LabelBusinessActivities2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current paid up Capital.
        /// </summary>
        public static string LabelCurrentPaidUpCapital {
            get {
                return ResourceManager.GetString("LabelCurrentPaidUpCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current paid up Capital (Amount).
        /// </summary>
        public static string LabelCurrentPaidUpCapitalAmount {
            get {
                return ResourceManager.GetString("LabelCurrentPaidUpCapitalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current paid up Capital (Currency).
        /// </summary>
        public static string LabelCurrentPaidUpCapitalCurrency {
            get {
                return ResourceManager.GetString("LabelCurrentPaidUpCapitalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string LabelManagement {
            get {
                return ResourceManager.GetString("LabelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key person involved in the business operation and their tasks.
        /// </summary>
        public static string LabelManagement2 {
            get {
                return ResourceManager.GetString("LabelManagement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string TitleBusiness {
            get {
                return ResourceManager.GetString("TitleBusiness", resourceCulture);
            }
        }
    }
}
