//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClosDotNet.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CallReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CallReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClosDotNet.Resources.Resources.CallReportResources", typeof(CallReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Recipient.
        /// </summary>
        public static string LabelReportCurrentRecipient {
            get {
                return ResourceManager.GetString("LabelReportCurrentRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string LabelReportDetailAdditionalPurpose {
            get {
                return ResourceManager.GetString("LabelReportDetailAdditionalPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees *.
        /// </summary>
        public static string LabelReportDetailAttendees {
            get {
                return ResourceManager.GetString("LabelReportDetailAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Call *.
        /// </summary>
        public static string LabelReportDetailCallDate {
            get {
                return ResourceManager.GetString("LabelReportDetailCallDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Call *.
        /// </summary>
        public static string LabelReportDetailCallPurpose {
            get {
                return ResourceManager.GetString("LabelReportDetailCallPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode of Contact *.
        /// </summary>
        public static string LabelReportDetailContactMode {
            get {
                return ResourceManager.GetString("LabelReportDetailContactMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string LabelReportDetailCustomerName {
            get {
                return ResourceManager.GetString("LabelReportDetailCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow-Up *.
        /// </summary>
        public static string LabelReportDetailFollowUp {
            get {
                return ResourceManager.GetString("LabelReportDetailFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Call.
        /// </summary>
        public static string LabelReportDetailPreviousCallDate {
            get {
                return ResourceManager.GetString("LabelReportDetailPreviousCallDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Report Ref No.
        /// </summary>
        public static string LabelReportDetailReferenceNo {
            get {
                return ResourceManager.GetString("LabelReportDetailReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Visit Date *.
        /// </summary>
        public static string LabelReportDetailSiteVisitDate {
            get {
                return ResourceManager.GetString("LabelReportDetailSiteVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Call.
        /// </summary>
        public static string LabelReportListCallDate {
            get {
                return ResourceManager.GetString("LabelReportListCallDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Call.
        /// </summary>
        public static string LabelReportListCallPurpose {
            get {
                return ResourceManager.GetString("LabelReportListCallPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated Date.
        /// </summary>
        public static string LabelReportListLastUpdatedDate {
            get {
                return ResourceManager.GetString("LabelReportListLastUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originator.
        /// </summary>
        public static string LabelReportListOriginator {
            get {
                return ResourceManager.GetString("LabelReportListOriginator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Report Ref No.
        /// </summary>
        public static string LabelReportListRefNo {
            get {
                return ResourceManager.GetString("LabelReportListRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string LabelReportListStatus {
            get {
                return ResourceManager.GetString("LabelReportListStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string LabelReportListWorkflow {
            get {
                return ResourceManager.GetString("LabelReportListWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action *.
        /// </summary>
        public static string LabelReportSubmitAction {
            get {
                return ResourceManager.GetString("LabelReportSubmitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer.
        /// </summary>
        public static string LabelReportSubmitReviewer {
            get {
                return ResourceManager.GetString("LabelReportSubmitReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Bank.
        /// </summary>
        public static string OptionContactModeAtBank {
            get {
                return ResourceManager.GetString("OptionContactModeAtBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Client Office.
        /// </summary>
        public static string OptionContactModeAtClientOffice {
            get {
                return ResourceManager.GetString("OptionContactModeAtClientOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Phone.
        /// </summary>
        public static string OptionContactModeByPhone {
            get {
                return ResourceManager.GetString("OptionContactModeByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Location.
        /// </summary>
        public static string OptionContactModeOtherLocation {
            get {
                return ResourceManager.GetString("OptionContactModeOtherLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubTitleSubmit {
            get {
                return ResourceManager.GetString("SubTitleSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Report.
        /// </summary>
        public static string TitleCallReportDetails {
            get {
                return ResourceManager.GetString("TitleCallReportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Report Listing.
        /// </summary>
        public static string TitleReportList {
            get {
                return ResourceManager.GetString("TitleReportList", resourceCulture);
            }
        }
    }
}
