//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClosDotNet.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClosDotNet.Resources.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate LOS (.Net).
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string ButtonAddNew {
            get {
                return ResourceManager.GetString("ButtonAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from Business Address.
        /// </summary>
        public static string ButtonCopyBusinessAddress {
            get {
                return ResourceManager.GetString("ButtonCopyBusinessAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from Home Address.
        /// </summary>
        public static string ButtonCopyHomeAddress {
            get {
                return ResourceManager.GetString("ButtonCopyHomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string ButtonCreateNew {
            get {
                return ResourceManager.GetString("ButtonCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Company.
        /// </summary>
        public static string ButtonCreateNewCompany {
            get {
                return ResourceManager.GetString("ButtonCreateNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Individual.
        /// </summary>
        public static string ButtonCreateNewIndividual {
            get {
                return ResourceManager.GetString("ButtonCreateNewIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string ButtonProcess {
            get {
                return ResourceManager.GetString("ButtonProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Search.
        /// </summary>
        public static string ButtonReturnToSearch {
            get {
                return ResourceManager.GetString("ButtonReturnToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string ButtonSignin {
            get {
                return ResourceManager.GetString("ButtonSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove?.
        /// </summary>
        public static string LabelRemove {
            get {
                return ResourceManager.GetString("LabelRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/N.
        /// </summary>
        public static string LabelRowNumber {
            get {
                return ResourceManager.GetString("LabelRowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year(s).
        /// </summary>
        public static string LabelYears {
            get {
                return ResourceManager.GetString("LabelYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Report.
        /// </summary>
        public static string MenuCallReport {
            get {
                return ResourceManager.GetString("MenuCallReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID combination already exists..
        /// </summary>
        public static string MessageIdAlreadyExists {
            get {
                return ResourceManager.GetString("MessageIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount..
        /// </summary>
        public static string MessageInvalidAmount {
            get {
                return ResourceManager.GetString("MessageInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not given any access to the application..
        /// </summary>
        public static string MessageLoginFailed {
            get {
                return ResourceManager.GetString("MessageLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        public static string MessageRequiredField {
            get {
                return ResourceManager.GetString("MessageRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the information: .
        /// </summary>
        public static string MessageSaveError {
            get {
                return ResourceManager.GetString("MessageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information has been saved successfully..
        /// </summary>
        public static string MessageSaveSuccess {
            get {
                return ResourceManager.GetString("MessageSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string MessageWelcome {
            get {
                return ResourceManager.GetString("MessageWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string OptionNo {
            get {
                return ResourceManager.GetString("OptionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string OptionPleaseSelect {
            get {
                return ResourceManager.GetString("OptionPleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string OptionSave {
            get {
                return ResourceManager.GetString("OptionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string OptionYes {
            get {
                return ResourceManager.GetString("OptionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Approver.
        /// </summary>
        public static string RoleDescriptionCA {
            get {
                return ResourceManager.GetString("RoleDescriptionCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Manager.
        /// </summary>
        public static string RoleDescriptionRM {
            get {
                return ResourceManager.GetString("RoleDescriptionRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Manager (Team Lead).
        /// </summary>
        public static string RoleDescriptionRMTL {
            get {
                return ResourceManager.GetString("RoleDescriptionRMTL", resourceCulture);
            }
        }
    }
}
