//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClosDotNet.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClosDotNet.Resources.Resources.CustomerResources", typeof(CustomerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Account Opened.
        /// </summary>
        public static string LabelDetailAccountOpenedDate {
            get {
                return ResourceManager.GetString("LabelDetailAccountOpenedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bldg/Blk/Hse No..
        /// </summary>
        public static string LabelDetailAddressBlockNo {
            get {
                return ResourceManager.GetString("LabelDetailAddressBlockNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Name.
        /// </summary>
        public static string LabelDetailAddressBuildingName {
            get {
                return ResourceManager.GetString("LabelDetailAddressBuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/City.
        /// </summary>
        public static string LabelDetailAddressCity {
            get {
                return ResourceManager.GetString("LabelDetailAddressCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country *.
        /// </summary>
        public static string LabelDetailAddressCountry {
            get {
                return ResourceManager.GetString("LabelDetailAddressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Format *.
        /// </summary>
        public static string LabelDetailAddressFormat {
            get {
                return ResourceManager.GetString("LabelDetailAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Mail.
        /// </summary>
        public static string LabelDetailAddressHoldMail {
            get {
                return ResourceManager.GetString("LabelDetailAddressHoldMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBox/SINGPOST Box No..
        /// </summary>
        public static string LabelDetailAddressPoBox {
            get {
                return ResourceManager.GetString("LabelDetailAddressPoBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string LabelDetailAddressPostalCode {
            get {
                return ResourceManager.GetString("LabelDetailAddressPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storey.
        /// </summary>
        public static string LabelDetailAddressStorey {
            get {
                return ResourceManager.GetString("LabelDetailAddressStorey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string LabelDetailAddressStreet {
            get {
                return ResourceManager.GetString("LabelDetailAddressStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string LabelDetailAddressUnit {
            get {
                return ResourceManager.GetString("LabelDetailAddressUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string LabelDetailAge {
            get {
                return ResourceManager.GetString("LabelDetailAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string LabelDetailBirthDate {
            get {
                return ResourceManager.GetString("LabelDetailBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Business Operation *.
        /// </summary>
        public static string LabelDetailBusinessOperationCountry {
            get {
                return ResourceManager.GetString("LabelDetailBusinessOperationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIF/Prospect Customer No *.
        /// </summary>
        public static string LabelDetailCifNumber {
            get {
                return ResourceManager.GetString("LabelDetailCifNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification *.
        /// </summary>
        public static string LabelDetailClassification {
            get {
                return ResourceManager.GetString("LabelDetailClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Constitution *.
        /// </summary>
        public static string LabelDetailConstitution {
            get {
                return ResourceManager.GetString("LabelDetailConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Dependents.
        /// </summary>
        public static string LabelDetailDependentCount {
            get {
                return ResourceManager.GetString("LabelDetailDependentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Facility Granted.
        /// </summary>
        public static string LabelDetailFacilityGrantedDate {
            get {
                return ResourceManager.GetString("LabelDetailFacilityGrantedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Credit Granted Date.
        /// </summary>
        public static string LabelDetailFirstCreditGrantedDate {
            get {
                return ResourceManager.GetString("LabelDetailFirstCreditGrantedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender *.
        /// </summary>
        public static string LabelDetailGender {
            get {
                return ResourceManager.GetString("LabelDetailGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Education.
        /// </summary>
        public static string LabelDetailHighestEducation {
            get {
                return ResourceManager.GetString("LabelDetailHighestEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address *.
        /// </summary>
        public static string LabelDetailHomeAddress {
            get {
                return ResourceManager.GetString("LabelDetailHomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary ID *.
        /// </summary>
        public static string LabelDetailId {
            get {
                return ResourceManager.GetString("LabelDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Of Issue.
        /// </summary>
        public static string LabelDetailIdIssuedCountry {
            get {
                return ResourceManager.GetString("LabelDetailIdIssuedCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string LabelDetailIdNumber {
            get {
                return ResourceManager.GetString("LabelDetailIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LabelDetailIdType {
            get {
                return ResourceManager.GetString("LabelDetailIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Incorporation *.
        /// </summary>
        public static string LabelDetailIncorporationCountry {
            get {
                return ResourceManager.GetString("LabelDetailIncorporationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Incorporation.
        /// </summary>
        public static string LabelDetailIncorporationDate {
            get {
                return ResourceManager.GetString("LabelDetailIncorporationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Name *.
        /// </summary>
        public static string LabelDetailLegalName {
            get {
                return ResourceManager.GetString("LabelDetailLegalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address ^.
        /// </summary>
        public static string LabelDetailMailingAddress {
            get {
                return ResourceManager.GetString("LabelDetailMailingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Information not available.
        /// </summary>
        public static string LabelDetailMandatoryInfoNotAvailable {
            get {
                return ResourceManager.GetString("LabelDetailMandatoryInfoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string LabelDetailMaritalStatus {
            get {
                return ResourceManager.GetString("LabelDetailMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 50% of turnover?.
        /// </summary>
        public static string LabelDetailMoreThan50S35 {
            get {
                return ResourceManager.GetString("LabelDetailMoreThan50S35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelDetailName {
            get {
                return ResourceManager.GetString("LabelDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name *.
        /// </summary>
        public static string LabelDetailNameLine1 {
            get {
                return ResourceManager.GetString("LabelDetailNameLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality *.
        /// </summary>
        public static string LabelDetailNationality {
            get {
                return ResourceManager.GetString("LabelDetailNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Resident *.
        /// </summary>
        public static string LabelDetailPermanentResidentInd {
            get {
                return ResourceManager.GetString("LabelDetailPermanentResidentInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Legal Name.
        /// </summary>
        public static string LabelDetailPreviousLegalName {
            get {
                return ResourceManager.GetString("LabelDetailPreviousLegalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Name.
        /// </summary>
        public static string LabelDetailPreviousName {
            get {
                return ResourceManager.GetString("LabelDetailPreviousName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Salutation.
        /// </summary>
        public static string LabelDetailPreviousSalutation {
            get {
                return ResourceManager.GetString("LabelDetailPreviousSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Officer Name.
        /// </summary>
        public static string LabelDetailPrimaryOfficerName {
            get {
                return ResourceManager.GetString("LabelDetailPrimaryOfficerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string LabelDetailRace {
            get {
                return ResourceManager.GetString("LabelDetailRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Address ^.
        /// </summary>
        public static string LabelDetailRegisteredAddress {
            get {
                return ResourceManager.GetString("LabelDetailRegisteredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Since.
        /// </summary>
        public static string LabelDetailRelationshipSince {
            get {
                return ResourceManager.GetString("LabelDetailRelationshipSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence Details.
        /// </summary>
        public static string LabelDetailResidenceDetails {
            get {
                return ResourceManager.GetString("LabelDetailResidenceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Resident *.
        /// </summary>
        public static string LabelDetailResidentCountry {
            get {
                return ResourceManager.GetString("LabelDetailResidentCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership.
        /// </summary>
        public static string LabelDetailResidentialOwnership {
            get {
                return ResourceManager.GetString("LabelDetailResidentialOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of Stay.
        /// </summary>
        public static string LabelDetailResidentialStayLength {
            get {
                return ResourceManager.GetString("LabelDetailResidentialStayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since when.
        /// </summary>
        public static string LabelDetailResidentialStayStartDate {
            get {
                return ResourceManager.GetString("LabelDetailResidentialStayStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LabelDetailResidentialType {
            get {
                return ResourceManager.GetString("LabelDetailResidentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation *.
        /// </summary>
        public static string LabelDetailSalutation {
            get {
                return ResourceManager.GetString("LabelDetailSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstructured Address.
        /// </summary>
        public static string LabelDetailUnstructuredAddress {
            get {
                return ResourceManager.GetString("LabelDetailUnstructuredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Bank Since Date.
        /// </summary>
        public static string LabelDetailWithBankSinceDate {
            get {
                return ResourceManager.GetString("LabelDetailWithBankSinceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIF Number.
        /// </summary>
        public static string LabelSearchCifNumber {
            get {
                return ResourceManager.GetString("LabelSearchCifNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string LabelSearchCustomerId {
            get {
                return ResourceManager.GetString("LabelSearchCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter search criteria.
        /// </summary>
        public static string LabelSearchCustomerInstructions {
            get {
                return ResourceManager.GetString("LabelSearchCustomerInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelSearchCustomerName {
            get {
                return ResourceManager.GetString("LabelSearchCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Country.
        /// </summary>
        public static string LabelSearchIdIssuedCountry {
            get {
                return ResourceManager.GetString("LabelSearchIdIssuedCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string LabelSearchIdNumber {
            get {
                return ResourceManager.GetString("LabelSearchIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LabelSearchIdType {
            get {
                return ResourceManager.GetString("LabelSearchIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIF Number.
        /// </summary>
        public static string LabelSearchResultCifNumber {
            get {
                return ResourceManager.GetString("LabelSearchResultCifNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string LabelSearchResultCustomerName {
            get {
                return ResourceManager.GetString("LabelSearchResultCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Issued Country.
        /// </summary>
        public static string LabelSearchResultIdIssuedCountry {
            get {
                return ResourceManager.GetString("LabelSearchResultIdIssuedCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        public static string LabelSearchResultIdNumber {
            get {
                return ResourceManager.GetString("LabelSearchResultIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type.
        /// </summary>
        public static string LabelSearchResultIdType {
            get {
                return ResourceManager.GetString("LabelSearchResultIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Officer Name.
        /// </summary>
        public static string LabelSearchResultRMName {
            get {
                return ResourceManager.GetString("LabelSearchResultRMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        public static string TitleCompanyDetails {
            get {
                return ResourceManager.GetString("TitleCompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TitleCustomerAddress {
            get {
                return ResourceManager.GetString("TitleCustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Customer.
        /// </summary>
        public static string TitleCustomerSearch {
            get {
                return ResourceManager.GetString("TitleCustomerSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string TitleCustomerSearchResult {
            get {
                return ResourceManager.GetString("TitleCustomerSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Details.
        /// </summary>
        public static string TitleIndividualDetails {
            get {
                return ResourceManager.GetString("TitleIndividualDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM Reference.
        /// </summary>
        public static string TitleRmReference {
            get {
                return ResourceManager.GetString("TitleRmReference", resourceCulture);
            }
        }
    }
}
