//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClosDotNet.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClosDotNet.Resources.Resources.MenuResources", typeof(MenuResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved/Declined.
        /// </summary>
        public static string ApprovedDeclined {
            get {
                return ResourceManager.GetString("ApprovedDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Report.
        /// </summary>
        public static string BusinessReport {
            get {
                return ResourceManager.GetString("BusinessReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Report.
        /// </summary>
        public static string CallReport {
            get {
                return ResourceManager.GetString("CallReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Report - All.
        /// </summary>
        public static string CallReportAll {
            get {
                return ResourceManager.GetString("CallReportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Origination Task(s).
        /// </summary>
        public static string CreditOriginationTask {
            get {
                return ResourceManager.GetString("CreditOriginationTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demographic.
        /// </summary>
        public static string CustomerDetails {
            get {
                return ResourceManager.GetString("CustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Customer.
        /// </summary>
        public static string CustomerSearch {
            get {
                return ResourceManager.GetString("CustomerSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        public static string Diary {
            get {
                return ResourceManager.GetString("Diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft(s).
        /// </summary>
        public static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry.
        /// </summary>
        public static string Enquiry {
            get {
                return ResourceManager.GetString("Enquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry - Enquiry Pending Recipient&apos;s Response.
        /// </summary>
        public static string EnquiryPendingRecipient {
            get {
                return ResourceManager.GetString("EnquiryPendingRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry - Enquiries Received.
        /// </summary>
        public static string EnquiryReceived {
            get {
                return ResourceManager.GetString("EnquiryReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry - Replies to Enquiries.
        /// </summary>
        public static string EnquiryReplied {
            get {
                return ResourceManager.GetString("EnquiryReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Management.
        /// </summary>
        public static string LeadManagement {
            get {
                return ResourceManager.GetString("LeadManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Concurrence/Approval.
        /// </summary>
        public static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending My Concurrence/Approval.
        /// </summary>
        public static string PendingMyApproval {
            get {
                return ResourceManager.GetString("PendingMyApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Approval Task(s).
        /// </summary>
        public static string PostApprovalTask {
            get {
                return ResourceManager.GetString("PostApprovalTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermSheet.
        /// </summary>
        public static string TermSheet {
            get {
                return ResourceManager.GetString("TermSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Sheet - Draft(s).
        /// </summary>
        public static string TermSheetDrafts {
            get {
                return ResourceManager.GetString("TermSheetDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Sheet - Pending My Concurrence/ Approval.
        /// </summary>
        public static string TermSheetPendingMyApproval {
            get {
                return ResourceManager.GetString("TermSheetPendingMyApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDF Module.
        /// </summary>
        public static string UDFModule {
            get {
                return ResourceManager.GetString("UDFModule", resourceCulture);
            }
        }
    }
}
