//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClosDotNet.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskListResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskListResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClosDotNet.Resources.Resources.TaskListResources", typeof(TaskListResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Call.
        /// </summary>
        public static string LabelReportListCallDate {
            get {
                return ResourceManager.GetString("LabelReportListCallDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Call.
        /// </summary>
        public static string LabelReportListCallPurpose {
            get {
                return ResourceManager.GetString("LabelReportListCallPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string LabelReportListCustomerName {
            get {
                return ResourceManager.GetString("LabelReportListCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Recipient.
        /// </summary>
        public static string LabelReportListLastRecipient {
            get {
                return ResourceManager.GetString("LabelReportListLastRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originator.
        /// </summary>
        public static string LabelReportListOriginator {
            get {
                return ResourceManager.GetString("LabelReportListOriginator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Report Ref No.
        /// </summary>
        public static string LabelReportListRefNo {
            get {
                return ResourceManager.GetString("LabelReportListRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string LabelReportListWorkflow {
            get {
                return ResourceManager.GetString("LabelReportListWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Report.
        /// </summary>
        public static string TitleReportList {
            get {
                return ResourceManager.GetString("TitleReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAFT.
        /// </summary>
        public static string TitleReportListDraft {
            get {
                return ResourceManager.GetString("TitleReportListDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMITTED.
        /// </summary>
        public static string TitleReportListSubmitted {
            get {
                return ResourceManager.GetString("TitleReportListSubmitted", resourceCulture);
            }
        }
    }
}
